if(!require(tuber)) install.packages('tuber')
if(!require(dplyr)) install.packages('dplyr')
if(!require(purrr)) install.packages('purrr')
if(!require(yaml)) install.packages('yaml')
if(!require(lubridate)) install.packages('lubridate')
if(!require(emayili)) install.packages('emayili')
if(!require(tictoc)) install.packages('tictoc')